defaults:
  - generator: beam_search
  - _self_
model_ckpt: "outputs/2024-11-24/10-07-24/checkpoints/ckpt_50000.pt"
attention_type: rope_attention
max_new_tokens: 300
input_text: "Long after the village lights had faded and the moon cast its silver glow over the empty fields, a figure moved silently along the forgotten road. Shadows stretched across the path, and the distant hoot of an owl echoed through the night. At the edge of the forest, where the trees stood like silent sentinels, there was a doorway carved into the ancient stone, hidden from all but the most watchful eyes. It was said that beyond the doorway lay secrets waiting to be uncovered, mysteries that only the brave could"
